### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/quanteda#1]
- [x] #2
https://docs.google.com/document/d/1wLdZBj2-cqEvSIfLAPJUS5Q1Vy2s5jAEilK6Wso8PQc/edit

 - [x] 2. Choose a topic for your software package - Done

 - [x] 3. Create project structure for the software package - In Progress

- [x] 3.1. Create the project structure for your software package appropriate for the language you have chosen, and push it as a public repository in the [UBC-MDS organization](https://github.com/UBC-MDS/) on Github.com.
   If you are choosing to work in the Python programming language, there is a quickstart guide for setting up the structure for Python project, you can find it [here](https://py-pkgs-cookiecutter.readthedocs.io/en/latest/quickstart.html). This time when you are prompted as whether to include GitHub Actions, say yes! In particular, choose option 3 (build + deploy).
   If you are choosing to work in the R programming language use the devtools and usethis package for setting up the structure for R project.

 - [x] 3.2. The name of the repository should be relevant to the package/project topics.

 - [x] 3.3. During project creation, you will be prompted to pick a license and for now choose the MIT license. You may change it later when you learn more about licenses.

 - [x] 3.4. Once the projects have been created, edit CONTRIBUTORS.md to add the contributor names (the students on the teams).

 - [x] 3.5. Edit CONDUCT.md to include the code of conduct for contributing to your project. The intention behind creating this file is fostering a healthy and positive work dynamic. Recall that you already have done something similar in DSCI 522, and you can start with that document and adapt it for your new team. Note that when you create the project structure with the methods above, a default version of this file will be created. You may choose to use it or adapt it with appropriate attributions.

 - [x] 3.6. Agree upon a collaboration strategy that describes how you will work together on this project (e.g., [GitHub flow](https://guides.github.com/introduction/flow/) and edit CONTRIBUTING.md to reflect your strategy. Again, there will be a default version of this file. You can use it as is or adapt it with appropriate attribution. Here are some example CONTRIBUTING.md files for your reference.

    - [Software Carpentry CONTRIBUTING.md](https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/CONTRIBUTING.md)
    - [factory_bot_rails CONTRIBUTING.md](https://github.com/thoughtbot/factory_bot_rails/blob/master/CONTRIBUTING.md)
    - [moby CONTRIBUTING.md](https://github.com/moby/moby/blob/master/CONTRIBUTING.md)

  - [x] #3
    - a summary paragraph that describes the project at a high level
    - a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)
    - a paragraph describing where your packages fit into the Python ecosystem (are there any other Python packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well).
  
 - [x] 4. Write function specifications and documentation
For this milestone you will write function documentation that will serve as specifications, but you will NOT write any code for your package functions. Specifically, set-up empty functions (with appropriate function names) containing no code in the files where you will eventually write code. Write function documentation (e.g., complete docstrings). These are the functions you wrote about in your proposal.

 - [x] 5. Manage issues professionally
Manage issues effectively through project boards and milestones, make it clear who is responsible for what and what project milestone each task is associated with. In particular, create an issue for each function in the package. Each of these issues must be assigned to a single person on the team. We want all of you to get coding experience in the project and each team member should be responsible for a package function. So if you are a team of four, you’ll be writing four functions for your package and if you are a team of three, you will be writing three functions for your package.

**Comment by JohnShiuMK** [comment]
meeting agenda today (2023-01-10):
 - [ ] create github issues for each task
 - [ ] create project board
 - [ ] create milestone 1
 - [ ] assign tasks

**Comment by dorisyycai** [comment]
Moving the TDL to issues

**Comment by meretelutz** [comment]
This week's tasks are completed. Good work everyone!
